Traceback (most recent call last):
  File "/data/gc/anaconda3/envs/lm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/gc/anaconda3/envs/lm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data3/gc/SeLM_v2/src/gpt.py", line 381, in <module>
    train_cte(cache_ckpt, gpt_ckpt, train_length, valid_length)
  File "/data/gc/anaconda3/envs/lm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data3/gc/SeLM_v2/src/gpt.py", line 310, in train_cte
    train_cache = load_file(os.path.join(cache_path, cache_cktp.format(train_length, 'train')), device='cpu')
  File "/data/gc/anaconda3/envs/lm/lib/python3.10/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError: No such file or directory: "./data/normed_b256_iters_3000_l256_train_filtered_onlylast.pth"
数据集总长度：1115394
